// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsipnbjrzygtdgmayfpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zaXBuYmpyenlndGRnbWF5ZnBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2MjYzMzksImV4cCI6MjA1NjIwMjMzOX0.W-SVvoMpm3_elWQPIIA0BjdQkQGiiVNLHUjhob_nqEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);